### ISSUE TITLE
Changed Functions

### ISSUE THREAD

**Issue by anxsaiyuki** [IndecipherableSuggestions/TagMeLegacy#7]

**Comment by anxsaiyuki** [comment]
Persistent Login
Can search by multiple Tags
New Tab that has the ranking for all the tags
Can click on tag to search for that tag
If using camera can detect location and display a map of the location
Can edit captions
Can add custom tags
Can delete memories

**Comment by cwillens** [comment]
Can click on location description to see all photos in that location
